### ISSUE TITLE
hass_apps v0.20180221.0 doesn't work with voluptuous 0.11 as needed by Home Assistant 0.64

### ISSUE THREAD

**Issue by heikland** [efficiosoft/hass_apps#5]
Running HA 0.64.0 in virtual env on Raspian Stretch
Running Appdaemon 2.1.12 (installed by "sudo pip3 install appdaemon"). **Demo apps works, no errors**.
Installed hass_apps  (installed by "sudo pip3 install --upgrade hass_apps")

When I trying to start appdaemon and Heaty I get several warnings.
I have no clues to what is wrong. 
Please advise.

pi@hassbian:~ $ /usr/local/bin/appdaemon -c /home/homeassistant/.homeassistant
2018-02-28 11:43:26.383643 INFO AppDaemon Version 2.1.12 starting
2018-02-28 11:43:26.384256 INFO Configuration read from: /home/homeassistant/.homeassistant/appdaemon.yaml
2018-02-28 11:43:26.522201 INFO Starting Apps
2018-02-28 11:43:26.774596 INFO Got initial state
2018-02-28 11:43:26.775945 INFO Loading Module: /home/homeassistant/.homeassistant/apps/hass_apps_loader.py
2018-02-28 11:43:26.823339 INFO Loading Object heaty_minimal using class HeatyApp from module hass_apps_loader
2018-02-28 11:43:27.264029 INFO heaty_minimal: --- heaty v0.11.0 initialization started
2018-02-28 11:43:27.287043 WARNING ------------------------------------------------------------
2018-02-28 11:43:27.287531 WARNING Unexpected error during loading of heaty_minimal:
2018-02-28 11:43:27.287877 WARNING ------------------------------------------------------------
2018-02-28 11:43:27.291935 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 912, in read_app
    init_object(name, class_name, module_name, conf.app_config[name])
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 583, in init_object
    conf.objects[name]["object"].initialize()
  File "/usr/local/lib/python3.5/dist-packages/hass_apps/common.py", line 86, in initialize
    self.cfg = self.Meta.config_schema(cfg)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/validators.py", line 284, in _exec
    raise e if self.msg is None else AllInvalid(self.msg)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/validators.py", line 282, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/schema_builder.py", line 769, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/schema_builder.py", line 587, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.5/dist-packages/voluptuous/schema_builder.py", line 425, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data['schedule_append']

2018-02-28 11:43:27.292486 WARNING ------------------------------------------------------------
2018-02-28 11:43:27.292847 INFO App initialization complete
2018-02-28 11:43:27.293615 INFO Dashboards are disabled
2018-02-28 11:43:27.293979 INFO API is disabled
2018-02-28 11:43:27.309815 INFO Connected to Home Assistant 0.64.0

[appdaemon.yaml.txt](https://github.com/efficiosoft/hass_apps/files/1766825/appdaemon.yaml.txt)
[apps.yaml.txt](https://github.com/efficiosoft/hass_apps/files/1766826/apps.yaml.txt)

**Comment by efficiosoft** [comment]
Well, this is due to a change in the voluptuous library which is used by Heaty for configuration parsing. It has been adapted in the master branch and will work again with next release.

Until then, you could separate HA and AppDaemon+hass_apps into separate virtualenvs (as I always suggest by the way) and force the previous version of voluptuous to be installed:

    python3 -m venv ad
    source ad/bin/activate
    pip install --upgrade appdaemon hass_apps
    pip install --upgrade voluptuous==0.10.5

**Comment by efficiosoft** [comment]
And please uninstall the system-wide stuff first.

**Comment by efficiosoft** [comment]
I updated the docs to explain how to install into a virtualenv properly:

http://hass-apps.readthedocs.io/en/latest/getting-started.html

**Comment by heikland** [comment]
Thanks for fast responding:-)
And it works now.
