### ISSUE TITLE
heaty: AttributeError: 'super' object has no attribute 'set_app_state'

### ISSUE THREAD

**Issue by marcinkowalczyk** [efficiosoft/hass_apps#6]
Hi,

 I've noticed following error with hass_apps-0.20180221.0.tar.gz (same on latest master) on HA 0.64.1 
```
2018-02-28 22:12:24.021760 WARNING AppDaemon: ------------------------------------------------------------
2018-02-28 22:12:24.022688 WARNING AppDaemon: Unexpected error in worker for App heaty:
2018-02-28 22:12:24.024902 WARNING AppDaemon: Worker Ags: {'name': 'heaty', 'id': UUID('f4a251cc-1923-4c4c-9685-a818c6312c5b'), 'type': 'timer', 'function': <bound method HeatyApp.publish_state_timer_cb of <hass_apps.heaty.app.HeatyApp object at 0x7402c790>>, 'kwargs': {}}
2018-02-28 22:12:24.027386 WARNING AppDaemon: ------------------------------------------------------------
2018-02-28 22:12:24.030611 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 506, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.6/site-packages/hass_apps/heaty/app.py", line 244, in publish_state_timer_cb
    self.publish_state()
  File "/usr/lib/python3.6/site-packages/hass_apps/heaty/app.py", line 923, in publish_state
    self.set_app_state(entity_id, state)
  File "/usr/lib/python3.6/site-packages/hass_apps/common.py", line 106, in set_app_state
    super().set_app_state(entity_id, state)  # pylint: disable=no-member
AttributeError: 'super' object has no attribute 'set_app_state'
2018-02-28 22:12:24.031639 WARNING AppDaemon: ------------------------------------------------------------

```

It was reported by other user here: https://community.home-assistant.io/t/heaty-a-flexible-heating-control-facilitating-schedules-and-manual-intervention/34958/224 

addon-appdaemon3: 0.1.0
ha: 0.64.1

**Comment by efficiosoft** [comment]
Are you sure it's the same with the master branch? It should have been fixed there.

**Comment by marcinkowalczyk** [comment]
Hi,

You are right, something went wrong with upgrade on 1st time. In Master it's ok now
